### ISSUE TITLE
Setting values for parameter "Maximal time since last run" seems to be mandatory

### ISSUE THREAD

**Issue by mbr2021** [jiuka/checkmk_windows_scheduled_task#2]
Release v2.1: If no values for "Maximal time since last run" are set in a given rule the check returns an error.

Exception:
`<AttributeError ('list' object has no attribute 'get')>`

Traceback:
  `<File "/omd/sites/mysite/lib/python3/cmk/base/checking.py", line 577, in get_aggregated_result
    result = _aggregate_results(check_function(**kwargs))
  File "/omd/sites/mysite/lib/python3/cmk/base/checking.py", line 808, in _aggregate_results
    perfdata, results = _consume_and_dispatch_result_types(subresults)
  File "/omd/sites/mysite/lib/python3/cmk/base/checking.py", line 852, in _consume_and_dispatch_result_types
    for subr in subresults:
  File "/omd/sites/mysite/lib/python3/cmk/base/api/agent_based/register/check_plugins.py", line 89, in filtered_generator
    for element in generator(*args, **kwargs):
  File "/omd/sites/mysite/local/lib/python3/cmk/base/plugins/agent_based/win_scheduled_task.py", line 88, in check_win_scheduled_task
    state = State(params['states'].get(task['lastResult'], params.get('else', 2)))>`

This seems to be new or a new option with version 2.1. It took me some time to find out that the cause was that simple so it might be changed or at least the information is helpful to someone updating from an earlier version of this plugin.

**Comment by jiuka** [comment]
Do you know how the configuration looked before? The configuration has changed internally but it was not expected to raise an exception with the old config still in place.

**Comment by mbr2021** [comment]
Here is my rule after checking "Maximal time since last run" and setting some values:

![Windows Scheduled Task](https://user-images.githubusercontent.com/81304968/112313429-1d5d9a00-8ca8-11eb-8bd1-c220ee157660.png)

I don't remeber if this checkbox "Maximal time since last run" (+ additional parameters below) has been there at all in version 1.1.  At least I know if it has been there it hasn't been configured by me. The "Service states" and "State if no entry matches" have been set in version 1.1.

**Comment by jiuka** [comment]
I could reproduce it. The problem was the changed config format. It only got updated when you (changed and) saved the rule. The bug is now fixed in #33d0ecb ans 2.2 will be released shortly. Thank you for reporting the issue.
