### ISSUE TITLE
Support of checkMK version 2.2 not clear

### ISSUE THREAD

**Issue by Ronald-Kloust** [jiuka/checkmk_windows_scheduled_task#4]
Dear jiuka,

we are using your extensionpackage win_scheduled_task v2.2 in our Distributed Installation (1 Master site and 9 Subsites) of checkMK.

I've updated our Distributed Installation from version 2.1.0p28 to 2.2.0p3. During the checkMK update a message came up that the win_scheduled_task package is not supported under checkMK v2.2.0. In the extension manager the package entry shows that wwin_scheduled_task 2.2 supports all checkMK version from 2.0.0 until 2.1.0.

Have you planned to create a new version of win_scheduled_task which supports the newer checkMK versions? Will it be relleases in the checkMK exchange area or here in Github?

Thank you in advance
Ronald Kloust

Ronald.Kloust@dlr.de

**Comment by jiuka** [comment]
Hi Ronald

A new Release is available here on Github. It is uploaded on the exchange, but it can take some time until it is reviewed.

Regards Marius

**Comment by Ronald-Kloust** [comment]
Hi Marius,

thank you for releasing version 2.4.0 so fast. I hope that it will work for more than this checkMK release. And as you believe it or not it's already available in the Checkmk exchange portal.

Regards, Ronald
